### ISSUE TITLE
GUI Text Editor for Docker Containers

### ISSUE THREAD

**Issue by johannesburg** [prl-mushr/mushr_sim#4]
New MuSHR users might not be familiar with text editors like vim, nano, or emacs that can be used in the Docker container. It would be a worthwhile investment to make it possible for them to launch a graphical editor like VS Code, Sublime or Atom from inside the docker container. I've seen this before, so bundling that with our quickstart would be a good idea--then for the `Going Further` section, we can have them launch the editor and change a couple lines of code (like, change the car's color or default speed).

**Comment by Rockett8855** [comment]
We decided to not use docker for the simulator.
